class Solution {
public:


    int memo(int n, unordered_map<int,int> *cache){
        if(n<=2){
            return n;
        }

        if(cache->count(n)){
            return (*cache)[n];
        }

        int result = memo(n - 1, cache) + memo(n - 2, cache);
        cache->insert({n, result});
        return cache->at(n);


    }
    int climbStairs(int n) {
        unordered_map<int,int> cache;
        return memo(n,&cache);
    }
};

/*
* What is known:
* Combinations are determined by placement of steps ie 2+1 != 1+2 
* There will always be the base case where walker goes one step at a time (1 + 1) repeating n times
* The number of combinations = n ends when n=4:
                                            n=4
                                            1+1+1+1 = 4 //combo 1
                                            1+1+2 = 4 //combo 2
                                            2+2 = 4 //combo 3
                                            2+1+1 = 4 //combo 4
                                            1+2+1 = 4 //combo 5
                                            n=5
                                            1+1+1+1+1 = 5 //combo 1
                                            1+2+2 = 5 //combo 2
                                            2+1+2 = 5 //combo 3
                                            2+2+1 = 5 //combo 4
                                            1+1+1+2 = 5 //combo 5
                                            1+1+2+1 = 5 //combo6
                                            1+2+1+1 = 5 //combo 7
                                            2+1+1+1 = 5 //combo8
* Each combination can be reduced into two Piles of combinations ending with a two step or a one step
* Approach: Use the DP implementation of a fibbonacci sequence to find the number of unique combinations
* Create a function memo that uses memoization to compute the fibonacci sequence for F(n) 
* with parameters n and a pointer to an unordered_map cache so the contents of the map don't get copied every time the function is called.
* Check if n <= 2 which is the upper bound of the two base cases {n==1,n==2}: if so return n.
* Check if the key value n exists in the cache already: if so return the value corresponding to key n in the cache.
* Initialize an int result that records the result of memo(n-1,cache) + memo(n-2,cache).
*   This will eventually reduce down to the base cases and then using the values generated by the base cases, populate result up to n.
* Insert the result into cache at key n.
* Return the value corresponding to key n.
*
* In the climbStairs() function initialize an unordered_map<int,int> cache.
* Then return number of distinct combinations of n by calling memo and passing in n and a reference to cache.
* 
*/